name: Build and Release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build:
    name: Build and Release for multiple platforms
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        arch: [amd64, arm64]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.23'

      - name: Install dependencies
        run: |
          make install-deps

      - name: Build for ${{ matrix.os }} on ${{ matrix.arch }}
        run: |
          if [ "${{ matrix.os }}" == "ubuntu-latest" ]; then
            export GOOS=linux
          elif [ "${{ matrix.os }}" == "macos-latest" ]; then
            export GOOS=darwin
          elif [ "${{ matrix.os }}" == "windows-latest" ]; then
            export GOOS=windows
            export BINARY_NAME=pongo.exe
          fi

          export GOARCH=${{ matrix.arch }}
          make build

      - name: Archive built binaries
        run: |
          mkdir -p dist/${{ matrix.os }}-${{ matrix.arch }}
          mv pongo* dist/${{ matrix.os }}-${{ matrix.arch }}/

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.os }}-${{ matrix.arch }}-pongo
          path: dist/${{ matrix.os }}-${{ matrix.arch }}

  release:
    name: Create Release
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Upload Release Binaries
        uses: softprops/action-gh-release@v1
        with:
          files: dist/**/*

        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

